import type { Metadata } from "next";
import { Asap } from "next/font/google";
import "./globals.css";
import PageHeader from "@/components/Header/PageHeader";
import PageFooter from "@/components/Footer/PageFooter";

const asap = Asap({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${asap.className} antialiased flex flex-col h-[100dvh] `}
      >
        <PageHeader />

        <main className="flex-1 bg-zinc-800">{children}</main>        

        <PageFooter />
      </body>
    </html>
  );
}